# Numpy

---

Numpy stands for `numerical python` and is core library for numeric and scientific computing.

It consists of multi-dimensional array objects and a collection of routines for processing those arrays.

In [1]:
import numpy as np

In [2]:
# array from list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [3]:
# single dimensional array
array_1d = np.array([10, 20, 30, 40, 50])
array_1d

array([10, 20, 30, 40, 50])

In [4]:
# check type of array
type(array_1d)

numpy.ndarray

`numpy.ndarray` means `n dimensional array`

In [5]:
# multi-dimensional array
array_2d = np.array([[10, 20, 30, 40, 50], [50, 40, 30, 20, 10]])
array_2d

array([[10, 20, 30, 40, 50],
       [50, 40, 30, 20, 10]])

In [6]:
# check type of array
type(array_2d)

numpy.ndarray

### zeros()

In [7]:
# intializing 1x2 (1 row x 2 column) NumPy array with zeros
np.zeros((1,2))

array([[0., 0.]])

In [8]:
# intializing 5x5 (5 row x 5 column) NumPy array with zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### full()

In [9]:
# initialize 1x2 (3 row x 3 column) NumPy array with same number (10 in this case)
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### arange()

In [10]:
# initialize NumPy array within a range
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
# initialize NumPy array within a range with step 5
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

### randint()

In [12]:
# initialize NumPy array with random numbers
# get 5 random numbers between range 1 to 100
np.random.randint(1, 100, 5)

array([38, 81, 83, 23, 75])

### NumPy array `shape`

In [13]:
# check shape 2d array
array_2d.shape

(2, 5)

`(2, 5)` implies array has 2 rows and 5 columns

In [14]:
# view original array
array_2d

array([[10, 20, 30, 40, 50],
       [50, 40, 30, 20, 10]])

In [15]:
# change shape of array
array_2d.shape = (5, 2)
array_2d.shape

(5, 2)

In [16]:
# view reshaped array
array_2d

array([[10, 20],
       [30, 40],
       [50, 50],
       [40, 30],
       [20, 10]])

### Join NumPy array

### vstack()

In [17]:
# define two arrays
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([11, 12, 13, 14, 15])

# stack arrays vertically
np.vstack((array_1, array_2))

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

### hstack()

In [18]:
# stack arrays horizontally
np.hstack((array_1, array_2))

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15])

### column_stack()

In [19]:
# stack arrays in column stack
np.column_stack((array_1, array_2))

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15]])

### NumPy Intersection & Diffrence

### intersect1d()

In [20]:
# re-define two arrays
array_1 = np.array([10, 20, 30, 40, 50, 60])
array_2 = np.array([50,60, 70, 80, 90, 100])

# find common values between 2 arrays
np.intersect1d(array_1, array_2)

array([50, 60])

### setdiff1d()

In [21]:
# array_1 - array_2
np.setdiff1d(array_1, array_2)

array([10, 20, 30, 40])

In [22]:
# # array_2 - array_1
np.setdiff1d(array_2, array_1)

array([ 70,  80,  90, 100])

### Addition of NumPy arrays

In [23]:
# define two arrays
array_3 = np.array([10, 20])
array_4 = np.array([30, 40])

# find sum of arrays
np.sum([array_3, array_4])

100

In [24]:
# find column wise sum
np.sum([array_3, array_4], axis=0)

array([40, 60])

In [25]:
# find row wise sum
np.sum([array_3, array_4], axis=1)

array([30, 70])

### NumPy Array Mathematics

In [26]:
# define array
array_5 = np.array([10, 20, 30, 40, 50, 60, 70])

# add 1 to each element of array
array_5 + 1

array([11, 21, 31, 41, 51, 61, 71])

In [27]:
# multiply each element of array by 2
array_5 * 2

array([ 20,  40,  60,  80, 100, 120, 140])

In [28]:
# substract 1 from each element of array
array_5 - 1 

array([ 9, 19, 29, 39, 49, 59, 69])

In [29]:
# divide each element of array by 2
array_5/2 

array([ 5., 10., 15., 20., 25., 30., 35.])

### mean()

In [30]:
# find mean of array
np.mean(array_5)

40.0

In [31]:
# find mean of random array
np.mean(np.random.randint(1, 50, 15))

23.866666666666667

### std()

In [32]:
# find standard deviation
np.std(array_5)

20.0

In [33]:
# find standard deviation of random array
np.std(np.random.randint(1, 50, 15))

13.0843417870369

### median()

In [34]:
# find median of array
np.median(array_5)

40.0

In [35]:
# find median of array of random array
np.median(np.random.randint(1, 50, 15))

38.0

### percentile()

In [36]:
# get diffrenct percentiles of array
print('25th percentile of array:', np.percentile(array_5, 25))
print('50th percentile of array:', np.percentile(array_5, 50))
print('75th percentile of array:', np.percentile(array_5, 75))

25th percentile of array: 25.0
50th percentile of array: 40.0
75th percentile of array: 55.0


### linspace()

function returns number spaces evenly w.r.t interval

In [37]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [38]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

### reshape()

In [39]:
# creating a numpy array
array_6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# print array shape
print('array shape:', array_6.shape, end='\n\n')

# print array size
array_size = array_6.size
print('array size:', array_size, end='\n\n')

# N-D array N dimension
N = 4
 
# calculating M
M = array_size//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped_1 = array_6.reshape((N, M))
print(f'reshaped array: {N} x {M}')
print(reshaped_1, end='\n\n')

# creating another reshaped array
reshaped_2 = np.reshape(array_6, (2, 8))
print(f'reshaped array: {reshaped_2.shape}')
print(reshaped_2)

array shape: (16,)

array size: 16

reshaped array: 4 x 4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

reshaped array: (2, 8)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


### copyto()

In [40]:
# make an array with numpy
original_array = np.array([1, 2, 3])
numbers_list = [4, 5, 6]
print('original array before copy:', original_array)
         
# applying numpy.copyto() method
np.copyto(original_array, numbers_list)
print('original array after copy:', original_array)

original array before copy: [1 2 3]
original array after copy: [4 5 6]


### transpose()

In [41]:
# make matrix with numpy
my_matrix = np.matrix('[4, 1; 12, 3]')

# applying matrix.transpose() method
my_matrix.transpose()

matrix([[ 4, 12],
        [ 1,  3]])

### NumPy Save & Load

### save()

In [42]:
# save NumPy array
np.save('my_array', array_5)

### load()

In [43]:
# load saved NumPy array
np.load('my_array.npy')

array([10, 20, 30, 40, 50, 60, 70])